CREATE TABLE storyboard_details (
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(1000),
  CREATED_BY INTEGER NOT NULL,
  CREATED_ON timestamp without time zone NOT NULL
  DEFAULT (current_timestamp AT TIME ZONE 'UTC'));