CREATE TABLE card (
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(1023),
  SWIMLANE_ID INTEGER NOT NULL,
  CONSTRAINT card_swimlanes_fk_1 FOREIGN KEY (SWIMLANE_ID) REFERENCES swimlane (id)
);